# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'easymoney' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for easymoney

  target 'easymoney-tvOSTests' do
    inherit! :search_paths

    # Pods for testing
    pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  end

  target 'easymoneyTests' do
    inherit! :search_paths

    # Pods for testing
  end

end
